testing/e2e/endpoint_ready_test.py
Related: kubeflow/kubeflow#4442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/75)
=> fix endpoint test json field name

prow_config.yaml
Follow up of https://github.com/kubeflow/kubeflow/pull/4476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/83)
=> add presubmit tests

prow_config.yaml, testing/workflows/components/params.libsonnet, testing/workflows/components/unit_tests.jsonnet
Related: #26 
Enable unittests in kfctl repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/87)
=> Enable Unittest

py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/95)
=> Disable failed tests due to ksonnet

pkg/kfconfig/loaders/v1beta1.go
Removes the hack in loaders/v1beta1.go because previously we have deps issue.
Related: #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/100)
=> directly use plugin types in v1beta1.go

prow_config.yaml
/assign @yanniszark @gabrielwen 
kubeflow/kubeflow#4501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/96)
=> Update prow config to kfctl_istio_dex config

pkg/apis/apps/kfconfig/types_test.go
Addresses kubeflow/kubeflow#4162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/107)
=> Add tests to KfConfig v1beta1

py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Addresses issue: https://github.com/kubeflow/kfctl/issues/105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/106)
=> kfctl binary push to GCS

cmd/kfctl/cmd/delete.go, pkg/kfconfig/loaders/v1.go, pkg/kfconfig/loaders/v1beta1.go, py/kubeflow/kfctl/testing/pytests/kfctl_delete_test.py
This is GCP specific flag and is already moved to KfGcpPlugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/120)
=> remove delete_storage flag

py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py, py/kubeflow/kfctl/testing/pytests/conftest.py, py/kubeflow/kfctl/testing/pytests/kfctl_go_test.py
to fix periodic test failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/132)
=> self signed cert for testing

py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py, py/kubeflow/kfctl/testing/pytests/pytorch_job_deploy.py, py/kubeflow/kfctl/testing/pytests/testdata/pytorch_job.yaml
Related: #97 
Rewrite pytorch job E2E test in pytest.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/137)
=> Pytorch pytest

pkg/kfapp/gcp/gcp.go
Fixes #143
there are cases service account is other type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/144)
=> fix the bug that only recognize iam service account

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py, py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Add pytest support to KfDef v1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/147)
=> add v1 support to E2E test

pkg/kfapp/gcp/gcp.go
Related: #124 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/148)
=> Automated cherry pick of #144: fix the bug that only recognize iam sa

Makefile
Fixes #161 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/162)
=> Fix Makefile for Darwin

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/163)
=> Automated cherry pick of #162: Fix Makefile for Darwin Cherry pick of #162 on v0.7-branch. #162: Fix Makefile for Darwin

Makefile, go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/164)
=> Fix makefile issue

py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
following https://github.com/kubeflow/kubeflow/pull/4633
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/165)
=> update profile test dir in e2e test

pkg/kfconfig/loaders/loaders_test.go, pkg/kfconfig/loaders/testdata/kfconfig_v1.yaml, pkg/kfconfig/loaders/testdata/kfconfig_v1beta1.yaml, pkg/kfconfig/loaders/testdata/kfctl_gcp_basic_auth.0.7.0.yaml, pkg/kfconfig/loaders/v1.go, pkg/kfconfig/loaders/v1beta1.go
related: https://github.com/kubeflow/kfctl/pull/179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/182)
=> unitest to make sure literal secrets are keeped during load kfdef -> kfconfig

pkg/kfconfig/types.go, pkg/kfupgrade/kfupgrade.go, prow_config.yaml, py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py, py/kubeflow/kfctl/testing/ci/kfctl_upgrade_e2e_workflow.py, py/kubeflow/kfctl/testing/pytests/conftest.py, py/kubeflow/kfctl/testing/pytests/kfctl_upgrade_test.py, py/kubeflow/kfctl/testing/util/kfctl_go_test_utils.py
Part of https://github.com/kubeflow/kubeflow/issues/3727
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/172)
=> Kfctl upgrade e2e test

OWNERS
Will be reviewing code from IBM side on Operator work, and contributing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/181)
=> Adding myself in Owners file

py/kubeflow/kfctl/testing/pytests/kfam_test.py
Currently the test might be flaky:
If we `get` directly after `create`,  the new profile might not exist yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/190)
=> add retry to kfam e2e test

README.md, operator.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/203)
=> Add a pointer for kfdef usage, and fix dome docs issues

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py, py/kubeflow/kfctl/testing/test_deploy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/198)
=> Fix katib deployment tests

pkg/kfupgrade/kfupgrade.go, prow_config.yaml, py/kubeflow/kfctl/testing/pytests/kfam_test.py
https://github.com/kubeflow/kfctl/issues/195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/207)
=> Update kfctl test to v0.7.1 -> v1.0.0

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py, py/kubeflow/kfctl/testing/test_deploy.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/216)
=> Update katib deployment tests

pkg/kfapp/gcp/gcp.go, py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/218)
=> Fix kfctl_second_apply test

pkg/kfapp/gcp/gcp.go, py/kubeflow/kfctl/testing/pytests/kfctl_second_apply.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/219)
=> Automated cherry pick of #218: test Cherry pick of #218 on v1.0-branch. #218: test

cmd/kfctl/cmd/apply.go, cmd/kfctl/cmd/build.go, pkg/kfapp/kustomize/kustomize.go
Fixes  https://github.com/kubeflow/kfctl/issues/233
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/234)
=> Update config file names to 1.0

py/kubeflow/kfctl/testing/pytests/jupyter_test.py, py/kubeflow/kfctl/testing/pytests/testdata/jupyter_test.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/230)
=> Update jupyter_test using v1 spec

cmd/kfctl/cmd/apply.go, cmd/kfctl/cmd/build.go, pkg/kfapp/kustomize/kustomize.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/238)
=> Automated cherry pick of #234: Update config file names Cherry pick of #234 on v1.0-branch. #234: Update config file names

pkg/mirror/mirror_image.go, pkg/mirror/testdata/expected-kustomization.yaml
fix bug for `mirror overwrite `
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/239)
=> mirror overwrite: drop image tags before write back

Makefile, operator.md
Add new makefile command for operator build to simplify the development build process. 
/assign @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/244)
=> update operator build instruction using makefile

OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/261)
=> reviewers for operator related issues and PRS

operator.md
Made some changes to install instructions, as well as pointed to the operator on operatorhub
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/275)
=> streamline operator install steps

pkg/kfconfig/types.go, pkg/kfconfig/types_test.go
Closes #260 
There are two symptoms reported in the above issue. One is the error `Filename too long`. The other one is the disk space under the local manifests repo will keep growing (7GB+) if keep trying the command.
The error message does not provide a good explanation of what the problem really is yet some file disk copy does not get cleaned up.
This PR aims to return a better error message and exit if the cache directory for the manifests is actually a sub directory of the manifests repo itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/272)
=> Return error when the cache path is a sub directory of local manifests repo

pkg/kfapp/kustomize/kustomize_test.go, pkg/kfapp/kustomize/testdata/doc.go, pkg/kfapp/kustomize/testdata/operator/base/kustomization.yaml, pkg/kfapp/kustomize/testdata/operator/base/service.yaml, pkg/kfapp/kustomize/testdata/operator/expected/service.yaml, pkg/kfapp/kustomize/testdata/operator/kustomization.yaml
Closes #289 
Added one unit test to check the ownerReference is correctly added through the new function.
=> add unit test

pkg/utils/k8utils.go
Reverts kubeflow/kfctl#131
See https://github.com/kubeflow/kfctl/issues/296
=> Revert "Enable istio injection in Kubeflow namespace"

pkg/kfapp/aws/k8sClient.go
Resolves #298 
Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>
=> Support KUBECONFIG environment in building k8s client

OWNERS
I will be primarily maintaining the code for kubeflow operator and contribution from IBM. Below is a list of PRs I have contributed to this repo and operator-framework/community-operator:
https://github.com/kubeflow/kfctl/pull/257
https://github.com/kubeflow/kfctl/pull/292
https://github.com/kubeflow/kfctl/pull/285
https://github.com/kubeflow/kfctl/pull/272
https://github.com/kubeflow/kfctl/pull/271
https://github.com/kubeflow/kfctl/pull/270
https://github.com/kubeflow/kfctl/pull/259
https://github.com/kubeflow/kfctl/pull/258
https://github.com/kubeflow/kfctl/pull/251
https://github.com/kubeflow/kfctl/pull/188
https://github.com/kubeflow/kfctl/pull/186
https://github.com/kubeflow/manifests/pull/550
https://github.com/operator-framework/community-operators/pull/1420 …
=> add myself to approver

OWNERS, operator.md
What is in this PR:
- adds the current tested operator image for each kfctl release
- adds operator reconciler handling of events
- revises some operator document wording
- adds myself back to reviewer so to receive review requests
=> update operator doc and add me back to reviewer

Dockerfile, Makefile
1. Adds support for building and releasing arm64 kfctl binary.
Note: This updated PR used a safer support method without changing current building targets and release names.
2. Fixes building error for target `build-kfctl-container` when executing `RUN go mod download` by upgrading the Golang version to v1.13.7.
3. Only installing google-cloud on x86_64 machines.
Signed-off-by: Henry Wang <Henry.Wang@arm.com>
=> Update: Enable arm64 kfctl binary build and fix docker build error

pkg/kfapp/aws/aws.go
Resolve #358  https://github.com/kubeflow/kubeflow/issues/5057
Change `kf-admin-${cluster-name}` to `kf-admin-${region}-${cluster-name}` for web identity role name
=> Add aws region into IRSA role name

pkg/kfapp/aws/aws.go, pkg/utils/iamutils.go
Code comes from #327, didn't hear back from original user for a while. I'd like to have this merged and released in next version.
=> Pretty print log messages IAM policy(from #327)

OWNERS
* Update OWNERS
Add some Red Hat approvers and reviewers to support repo activity
* Update OWNERS
=> Cherry pick #338 to v1.1-branch

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
/assign @jlewi 
Part of https://github.com/kubeflow/gcp-blueprints/issues/59
=> test(pipelines): update deployment list for test_pipeline_is_ready

pkg/kfapp/aws/aws.go, pkg/kfconfig/types.go, pkg/utils/awsutil.go
Make sure kfctl works for v3 manifests for AWS.
=> Adapt to v3 manifest for aws

pkg/kfapp/aws/aws.go, pkg/kfconfig/types.go, pkg/utils/awsutil.go
Cherry-pick kfctl AWS changes to v1.1-branch for release purpose.
=> Cherry pick #378 #379 #380 to v1.1-branch

OWNERS
Hi all, I have continuously contributed to `kubeflow/kfctl` repo and excited to continue working on it. 
Thus, I want to add myself into reviewer list to help kfctl grow fast.
The list of my PR on kfctl:
https://github.com/kubeflow/kfctl/pull/380
https://github.com/kubeflow/kfctl/pull/357
https://github.com/kubeflow/kfctl/pull/282
https://github.com/kubeflow/kfctl/pull/273
=> Add PatrickXYS into reviewer

pkg/kfapp/aws/OWNERS, pkg/kfconfig/awsplugin/OWNERS
To further maintain AWS resources, add PatrickXYS into AWS folders OWNERS
/cc @Jeffwan
=> Add Myself into AWS OWNERS

pkg/kfapp/kustomize/kustomize.go
Fixes https://github.com/kubeflow/kfctl/issues/412
=> fix: dump generate invalid yaml

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
/assign @PatrickXYS 
Part of https://github.com/kubeflow/metadata/issues/250
Dependency of https://github.com/kubeflow/manifests/pull/1619
=> test: remove metadata UI/server readiness test

py/kubeflow/kfctl/testing/pytests/kf_is_ready_test.py
This PR will pass tests until https://github.com/kubeflow/testing/pull/803 merged
=> Add daemonset status check support

cmd/manager/main.go
Update version output to 1.2.0 as requested in sub task in issue https://github.com/kubeflow/kfctl/issues/422
=> Update version output to 1.2.0

cmd/manager/main.go
Cherry pick to update version output to 1.2.0.
=> Update version output to 1.2.0 (#449)

pkg/kfconfig/types.go
Looks like all the nice functionality of go-getter was removed to work-around github's tarball download change.
This restores the functionality and keeps the http work-around
Fixes https://github.com/kubeflow/kfctl/issues/217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfctl/247)
=> Add back support for go-getter manifest repo uri's

py/kubeflow/kfctl/testing/ci/kfctl_e2e_workflow.py
Helps on https://github.com/kubeflow/testing/issues/861
=> Change S3 bucket to aws-kubeflow-jenkins
